#!/bin/bash


if [ "$1" == "start" ]; then

	sleep 60
	DBUS="$(cat /proc/$(pgrep gnome-session)/environ | grep DBUS_SESSION_BUS_ADDRESS)"

	while true; do

		JOB="$(ps axf | grep "gnome-session-inhibit --app-id playerguard" | grep -v grep)"

		if [ -f /tmp/playerguard-stop ]; then
			if [ "$JOB" != "" ]; then
				ps axf | grep "gnome-session-inhibit --app-id playerguard" | grep -v grep | awk '{print "kill -9 " $1}' | bash
			fi

			rm /tmp/playerguard-stop
			exit
		fi


		if [ "$(export $DBUS && playerctl status)" == "Playing" ]; then
			if [ "$JOB" == "" ]; then
				export $DBUS && gnome-session-inhibit --app-id playerguard --reason "audio/video player running" --inhibit idle:suspend sleep infinity &
				disown %
			fi
		else
			if [ "$JOB" != "" ]; then
				ps axf | grep "gnome-session-inhibit --app-id playerguard" | grep -v grep | awk '{print "kill -9 " $1}' | bash
			fi
		fi

		sleep 5

	done
else

	if [ "$1" == "stop" ]; then
		touch /tmp/playerguard-stop

	fi
fi