#!/bin/bash

WASCALL="0"

while true; do

if [ -e /dev/ttyUSB1 ]; then
	if [ "$(mmcli -m any --voice-list-calls)" != "No calls were found" ]; then
		WASCALL="1"
	else
		if [ "$WASCALL" == "1" ]; then
			systemctl --user restart pulseaudio
			WASCALL="0"
		fi
	fi

fi

sleep 5

done
