#!/bin/bash

ITMAC="cf:d8:a8:a7:66:da"

while true; do

if [ "$(bluetoothctl show | grep Powered | cut -d$'\t' -f 2 | cut -d ':' -f 2 | cut -d ' ' -f 2)" == "yes" ]; then
	if [ "$(bluetoothctl info $ITMAC | grep Connected | cut -d$'\t' -f 2 | cut -d ':' -f 2 | cut -d ' ' -f2)" == "no" ]; then
		bluetoothctl connect $ITMAC
		systemctl --user restart itd
	fi
fi


sleep 5

done
